version: '3.4'


networks:
  demoapp:


services:

 

  sql-myplace-db:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2019-latest

    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=Password123#@

    ports: 
     - 5003:1433
   
    networks:
    - demoapp
  web:
    depends_on:
     - sql-myplace-db
    image: ${DOCKER_REGISTRY-}web:latest
    container_name: my-place-backend
    build:
      context: .
      dockerfile: src/Web/Dockerfile

    ports:
      - "5000:5000"
      - "5001:5001"
    
    networks:
     - demoapp

  # runtrack-seg:
  #  image: datalust/seq:latest
  #  container_name: my-place.seq
  #  environment: 
  #  - ACCEPT_EULA=Y
  #  ports:
  #   - 5341:5341
  #   - 8003:83